### ISSUE TITLE
nodelist is empty

### ISSUE THREAD

**Issue by GrinOleksandr** [ivmelo/store-scrapper#2]
php app_store/tests/test.php
PHP Fatal error:  Uncaught InvalidArgumentException: The current node list is empty. in app_store\vendor\symfony\dom-crawler\Crawler.php:568
Stack trace:
#0 app_store\src\Ivmelo\StoreScraper\Scraper.php(146): Symfony\Component\DomCrawler\Crawler->text()
#1 app_store\tests\test.php(37): Ivmelo\StoreScraper\Scraper->getAppStoreAppData('https://itunes....')
#2 {main}
  thrown in app_store\vendor\symfony\dom-crawler\Crawler.php on line 568

**Comment by GrinOleksandr** [comment]
author is ignoring his project
